[package]
name = "awesome-project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
confy = "0.5.1"
rand = "0.8.5"
rand_distr = "0.4.3"
serde = "1.0.152"
serde_derive = "1.0.152"